import { GeistSans } from 'geist/font/sans'

import Lenis from './lenis'

import '@/styles/app.scss'

export const metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
    return (
        <html lang="fr">
            <body className={GeistSans.className}>
                <Lenis>{children}</Lenis>
            </body>
        </html>
    )
}
